/** Autogenerated Scala Code by ANTLR v4 parser.
  * Originally Developed by: Zayd Hammoudeh (zayd.hammoudeh@sjsu.edu)
  *   * Course: CS252 (Spring 2016)
  * Special Thanks to Dr. Thomas Austin (thomas.austin@sjsu.edu)
  */

object haskell_code {

  // Here's a comment.  
  def myFunc(___0___ : => List[Int], ___1___ : => Int) : Int = (___0___, ___1___) match {
      case (x, y) => 3 + 5
  } // End of function

  // Here's another one.  
  def myFunc2(___0___ : => Int, ___1___ : => Int, ___2___ : => Int) : Int = (___0___, ___1___, ___2___) match {
      case (x, y, z) => ( -3) * 9 * 10
  } // End of function

  def main(args : Array[String]){
     println(( myFunc2(3, 4, 5)).toString())
    } // End of function

}
